### PR TITLE
core: Fix compile issue under Java 8+

### PR DESCRIPTION
**Pull request by wltjr**
Fixes the following issue
https://issues.apache.org/jira/browse/JCLOUDS-1333

### CODE REVIEW

**Comment by wltjr** [comment]
Not sure why its showing it failed. It seemed to pass all tests and created a jar.

**Comment by nacx** [comment]
I think it failed due to `checkstyle`. Can you add an space before `Functions` at lines 102 and 189?

**Comment by wltjr** [comment]
Sure I didn't catch that, guess the compiler doesn't care. I am making the [changes on the fly](https://github.com/Obsidian-StudiosInc/os-xtoo/blob/master/dev-java/jclouds-core/jclouds-core-9999.ebuild#L55) at build time so kinda moot to me. But that hopefully explains the failure. Its nasty code...

Few others have some set as well, changing same stuff, ```getHostText``` to ```getHost```, and some static imports for like ```and()``` and ```or()`` [Predicates](https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Predicates.java) like in [compute](https://github.com/Obsidian-StudiosInc/os-xtoo/blob/master/dev-java/jclouds-compute/jclouds-compute-9999.ebuild#L55).

Otherwise got all switched over to guava 24, and gson 2.8.2 Pretty pleased as it was one of the few packages making me keep older guava. Now just 2 others to fix to get rid of guava 21.

**Comment by nacx** [comment]
Thanks for the PR @wltjr!

I've tried a local build with Java 8 and Guava 21.0 and it is still failing:

```bash
ibarrera@ibarrera:~/src/asf/jclouds $ mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00)
Maven home: /opt/maven
Java version: 1.8.0_91, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_91/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.14.18-300.fc27.x86_64", arch: "amd64", family: "unix"
```

And the failure:

```bash
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ jclouds-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 358 source files to /home/ibarrera/src/asf/jclouds/core/target/classes
/home/ibarrera/src/asf/jclouds/core/src/main/java/org/jclouds/reflect/Reflection2.java:199: error: <anonymous org.jclouds.reflect.Reflection2$5$1> is not abstract and does not override abstract method test(Invokable<?,?>) in Predicate
               Optional<Invokable<?, ?>> constructor = tryFind(constructors, new Predicate<Invokable<?, ?>>() {
                                                                                                              ^
/home/ibarrera/src/asf/jclouds/core/src/main/java/org/jclouds/reflect/Reflection2.java:267: error: <anonymous org.jclouds.reflect.Reflection2$7$1> is not abstract and does not override abstract method test(Invokable<?,?>) in Predicate
               Optional<Invokable<?, ?>> method = tryFind(methods, new Predicate<Invokable<?, ?>>() {
                                                                                                    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
```

It looks like the compiler is messing imports up and it is treating the predicate passed to the `tyFind` method as a `java.util.Predicate` instead of using the (properly imported) Guava one.

**Comment by wltjr** [comment]
@nacx are you getting that failure with my patches or in general?

Like in the [compute package](https://github.com/Obsidian-StudiosInc/os-xtoo/blob/master/dev-java/jclouds-compute/jclouds-compute-9999.ebuild#L55) I made. I had to change the static imports to regular usage. I guess that maybe a compiler bug/issue. The Class names can vary, as I saw it mixing Functions with Function. Though I found a [Function class in guava](https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Function.java) that was inheriting [Java internal Function](https://docs.oracle.com/javase/9/docs/api/java/util/function/Function.html#compose-java.util.function.Function-). It was still mixing [guava Functions](https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Functions.java) with internal Function. Thus this PR.

I suspect there are many things like that. Short of relying on the compiler. I would just remove static imports and change usage. Unless there is some reason for them to be static. Just seems like shorthand to get at the methods. Vs typing the class name over and over. Maybe more to it though.

**Comment by nacx** [comment]
I just compiled your branch, with the patch in this PR, with Java 8 and Guava 21.0 (see the command I used to build the project in my previous comment) and the build fails for the mentioned reason. It does not even try to build compute or other projects, as it fails to build `core`.

I mean, I have no issues with this patch, but it does not actually fix the `jclouds + Java8 + Guava>=21.0` issue.

**Comment by wltjr** [comment]
I do not have that build failure, or I would have addressed it. I can fix in the same branch and push. Did it build otherwise before? I thought that issue in Jira was open for it failing under 1.8 or something. Also I am using guava 24 and Java 9. Though I would imagine Java 9 to be pickier. I had Jclouds building under 1.8 before. I guess maybe my failing came with 9.

How come the CI build didn't fail? The patch doesn't really change anything to cause a failure. I think maybe its just not addressing all issues. Though not sure why I do not run into that. Maybe a guava issue. Can you try with gauva 24? Just curious, I can address either way. Likely just another static import change...

**Comment by wltjr** [comment]
@nacx there pushed with changes to that file. It was another static import issue... Just remove static, add class name to methods, and done. Maybe more though we will see. I did not run into that for what ever reason. Though the changes are safe for anyone. Just changing code syntax/semantics, not actual function.

**Comment by wltjr** [comment]
I build it differently straight javac basically. But you can see I am using [guava 24](https://github.com/Obsidian-StudiosInc/os-xtoo/blob/master/dev-java/jclouds-core/jclouds-core-9999.ebuild#L34). All the [jclouds packages I have are updated to guava 24](https://github.com/Obsidian-StudiosInc/os-xtoo/commits/master). But everything is the latest, auto, gson, guava, java 9. About to move onto 10. Though most things that are good under 9 seem to be under 10. Less any JNI stuff.

Which I guess I need to apply the compute changes to the patch as well. I guess you will run into some others. I can address. Though kinda wish I didn't open the box.

**Comment by wltjr** [comment]
Added patches for compute. To use Guava 22 you will need to switch from ```getHostText``` to ```getHost```. I can make that change but its no going back. It is deprecated in [guava 20](https://github.com/google/guava/blob/v20.0/guava/src/com/google/common/net/HostAndPort.java#L83) and [guava 21 ](https://github.com/google/guava/blob/v21.0/guava/src/com/google/common/net/HostAndPort.java#L92), but by [guava 22 getHostText is gone](https://github.com/google/guava/blob/v22.0/guava/src/com/google/common/net/HostAndPort.java). ```getHost``` is not in [guava <= 19](https://github.com/google/guava/blob/v19.0/guava/src/com/google/common/net/HostAndPort.java#L84). That is guava 20+

**Comment by wltjr** [comment]
See how that is, think I addressed the last checkstyle issue. If other build failures let me know and I will address. Though have to make a call on the guava 22+ vs 19-. From 20 on its not an issue. But supporting <20 and beyond >=22 will be an issue.

**Comment by nacx** [comment]
jclouds builds fine with Java 8. The problem arises when using Java 8 with Guava >= 21.0. The pull request builder does not force a concrete Guava version and builds the project with the default jclouds one, that's why the build succeeded.

You can easily reproduce the issue by passing the `-Dguava.version=21.0` to the Maven build to force a concrete version of Guava.

I've tried building the pull request with `oracle64-1.8.0.91` and `oracle64-1.8.0.162`, and using Guava 21.0, 22.0 and 24.0-jre. Always the same failure:

```bash
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ jclouds-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 358 source files to /home/ibarrera/src/asf/jclouds/core/target/classes
/home/ibarrera/src/asf/jclouds/core/src/main/java/org/jclouds/reflect/Reflection2.java:199: error: <anonymous org.jclouds.reflect.Reflection2$5$1> is not abstract and does not override abstract method test(Invokable<?,?>) in Predicate
               Optional<Invokable<?, ?>> constructor = Iterables.tryFind(constructors, new Predicate<Invokable<?, ?>>() {
                                                                                                                        ^
/home/ibarrera/src/asf/jclouds/core/src/main/java/org/jclouds/reflect/Reflection2.java:267: error: <anonymous org.jclouds.reflect.Reflection2$7$1> is not abstract and does not override abstract method test(Invokable<?,?>) in Predicate
               Optional<Invokable<?, ?>> method = Iterables.tryFind(methods, new Predicate<Invokable<?, ?>>() {
                                                                                                              ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
```

Can you try building the pull request using Guava 21.0, as mentioned in my previous comments? Obviously using an *unpatched* version of Guava or any other library jclouds depends on.

**Comment by wltjr** [comment]
For some reason usage is not inheriting [guava Predicate](https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Predicate.java#L78) implementation of [test](https://docs.oracle.com/javase/9/docs/api/java/util/function/Predicate.html#test-T-). 

This is really a mess, CI gives different failures than locally... What is going on with that?

Not sure what to say on guava versions but you all need to figure stuff out. You cannot support that many versions of guava with API changes. Like the removal of ```getHostText``` and ```getHost``` not being in < guuva 20. Also seems trying to support older targets has issues. I had odd maven failures with ```-Dmaven.compile.source=1.8 -Dmaven.compile.target=1.8```. Ended up running without which I guess uses target 1.6.

Not sure how much more time i want to spend on this. I have already fixed my issues. This seems like a can of works for JClouds. I also do not understand why the legacy guava and targets. It will cause issues like this as things move forward.

I would recommend at least requiring quava 22 and source/target 1.8.

**Comment by wltjr** [comment]
Maven is horrible and this is taking way to long to fix. I have to fix each class by class. Maven stops after first failure. In my environment I see all issues so I can address all at once. This is taking really long and is very inefficient style of development. About to switch over to looking for all use of Predicate...

**Comment by wltjr** [comment]
375 classes need be modified.... 

```
$ grep -l "import com.google.common.base.Predicate;" -r * | wc -l
375
```

I think I will avoid using jclouds and maybe remove from my package. This is insanity.... It also is not required in my env, so I am not sure why any of this is even necessary. This seems like legacy incompatibility....

As a project you all need to make some hard decisions. I maintain hundreds, over a thousand Java packages. This is one of the only with such legacy issues. The other is horrible lombok.... I would really recommend telling those with legacy needs to use older jclouds. For any newer releases really need to move to newer stuff. Or you will continue to be plagued and held back by odd issues like this. Which take considerable time to resolve.

I think I am about done here... The change seems pretty massive, and I feel like other issues in future. CI failing on overrides, which at some point would need to be in there. But why it cannot find the Guava implementation of ```test```. That to me seems like some legacy issue.

Under 1.8 it says it failed, but seems it compiled...
```bash
mvn clean install -Dguava.version=21.0 -pl :jclouds-core -am -Dmaven.compile.source=1.8 -Dmaven.compile.target=1.8 -Dmaven.test.skip=true
```

```bash
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ jclouds-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 358 source files to /projects/jclouds/core/target/classes
/projects/jclouds/core/src/main/java/org/jclouds/json/internal/NamingStrategies.java:264: warning: [cast] redundant cast to Predicate<Class<? extends Annotation>>
                     }).anyMatch((Predicate<Class<? extends Annotation>>) in(markers));
                                 ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jclouds-core ---
[INFO] Not copying test resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ jclouds-core ---
[INFO] Not compiling test sources
[INFO]
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ jclouds-core ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- animal-sniffer-maven-plugin:1.11:check (default) @ jclouds-core ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache jclouds Project ............................. SUCCESS [  3.787 s]
[INFO] jclouds shared Maven resources ..................... SUCCESS [  1.963 s]
[INFO] jclouds Components Core ............................ FAILURE [  6.262 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.459 s
[INFO] Finished at: 2018-02-16T13:36:46-05:00
[INFO] Final Memory: 81M/509M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.11:check (default) on project jclouds-core: Execution default of goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.11:check failed.: IllegalArgumentException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jclouds-core
```

Without the source/target I get different failures....
```bash
[INFO] Compiling 358 source files to /projects/jclouds/core/target/classes
/projects/jclouds/core/src/main/java/org/jclouds/json/internal/NamingStrategies.java:72: error: <anonymous org.jclouds.json.internal.NamingStrategies$NameExtractor$1> is not abstract and does not override abstract method test(Annotation) in Predicate
         this.predicate = new Predicate<Annotation>() {
                                                      ^
/projects/jclouds/core/src/main/java/org/jclouds/json/internal/NamingStrategies.java:189: error: <anonymous org.jclouds.json.internal.NamingStrategies$AnnotationFieldNamingStrategy$1> is not abstract and does not override abstract method test(Field) in Predicate
                  Iterable<Field> fields = filter(declaredFields, new Predicate<Field>() {
                                                                                         ^
/projects/jclouds/core/src/main/java/org/jclouds/json/internal/NamingStrategies.java:257: error: <anonymous org.jclouds.json.internal.NamingStrategies$AnnotationConstructorNamingStrategy$1> is not abstract and does not override abstract method test(Invokable<?,?>) in Predicate
         return new Predicate<Invokable<?, ?>>() {
                                                 ^
/projects/jclouds/core/src/main/java/org/jclouds/json/internal/NamingStrategies.java:264: warning: [cast] redundant cast to Predicate<Class<? extends Annotation>>
                     }).anyMatch((Predicate<Class<? extends Annotation>>) in(markers));
                                 ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
1 warning
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache jclouds Project ............................. SUCCESS [  3.789 s]
[INFO] jclouds shared Maven resources ..................... SUCCESS [  1.798 s]
[INFO] jclouds Components Core ............................ FAILURE [  4.468 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.437 s
[INFO] Finished at: 2018-02-16T13:40:15-05:00
[INFO] Final Memory: 79M/470M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jclouds-core: Compilation failure -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jclouds-core
```

**Comment by nacx** [comment]
>This is really a mess, CI gives different failures than locally... What is going on with that?

That's not really true. If you run the same build than the CI system, which is a standard Maven build, you'll get the same failures.

>You cannot support that many versions of guava with API changes. Like the removal of getHostText and getHost not being in < guava 20. Also seems trying to support older targets has issues.

We don't really support that many versions. We are very clear on what we support and are just a few range of JDK, Guice and Guava versions. You can see it in our [compatibility matrix](https://jclouds.ci.cloudbees.com/job/jclouds-compat/). Anything outside that matrix is not officially supported and you may find issues (like this already known issue when using Java 8 with Guava >= 21).

>Not sure how much more time i want to spend on this. I have already fixed my issues. This seems like a can of works for JClouds. I also do not understand why the legacy guava and targets. It will cause issues like this as things move forward.

And this is OK. You took your time to open a PR that you thought fixed the issue but then discovered that the issue was bigger than expected. We already knew that and had several discussions on the development mailing list regarding the best way to fix it, because we already went that path and ended up in finding some issues with the compiler. With my comments, (needless to say we highly appreciate all contributions) I just wanted to point out that the actual change was not enough to completely fix the issue and tried to explain how to build jclouds the standard way so you could properly reproduce the failures.

>Maven is horrible and this is taking way to long to fix. I have to fix each class by class. Maven stops after the first failure. In my environment, I see all issues so I can address all at once. This is taking really long and is a very inefficient style of development. About to switch over to looking for all use of Predicate...

You might find it useful if you run it with the "fail at end flag": `mvn -fae`

>As a project you all need to make some hard decisions. I maintain hundreds, over a thousand Java packages. This is one of the only with such legacy issues. The other is horrible lombok.... I would really recommend telling those with legacy needs to use older jclouds. For any newer releases really need to move to newer stuff. Or you will continue to be plagued and held back by odd issues like this. Which take considerable time to resolve.

As I said, we know the existing challenges we'll have to face when moving forward and upgrading JDK and dependencies. And we'll make that decision. Not a hard one, but a *community decision*. One/two years ago we could simply not require Java 8 and a modern Guava because many of our downstream users could not upgrade to modern Guava versions or newer JDKs. And we take backwards compatibility very seriously. I think now it is a bit different as Java 8 has been widely adopted and it is time to start planning for which release we will officially support Java 8 and decide which Guava versions we'll support. If we haven't done that before, it's not because "we don't care". Just the opposite. We care about our users and we try to make upgrades as pain-free as possible, even if that means not using cutting-edge libraries and JDKs for a while.

>I think I am about done here... The change seems pretty massive, and I feel like other issues in future. CI failing on overrides, which at some point would need to be in there. But why it cannot find the Guava implementation of test. That to me seems like some legacy issue.

Yes, the change could be big. But we still don't know. We still don't understand the cause of the root issue (the one I copied in my previous replies and the last one you pasted), and we need to do some research on that. Once that is done and the cause is properly understood and isolated we'll be able to properly determine the scope of the issue, the right fix, and the steps to upgrade to modern JDK and Guava versions.

I completely understand you may not have time to go through this, and it is OK. Thanks for the effort you put on this and for taking your time to have a look at it!

**Comment by wltjr** [comment]
I had local builds failing I forced pushed and passed CI. Which is why I was asking. What is odd is the amount of issues that came up as part of the PR that did not in my env. I was building it the standard way via maven, where I was getting the additional modifications. But I feel those are not necessary, more like a band aid that will cause problems later.

The changes really are not that big or require much modification. If you avoid guava 21. I do not see a path there. The community needs to discuss moving to guava 22+. Not supporting anything <= 22. There are API changes you cannot easily get around. Plus these odd issues I feel are specific to 21. I am not seeing any of this with guava 24 under Java 9, and I can test under 10. These are odd issues that come up with trying to use newer stuff in older JDKs.

I can appreciate some legacy compatibility, but the Java world has changed. There will be 4 releases a year. Even 9 is about to be replaced by 10 next month, in a few weeks. Anyone still stuck on 1.6, or 1.7. I feel is not forward looking. IMHO this is where situations like the Equifax Struts2 hack comes from. No one should be running Struts2 period, its like a decade old. Replaced by jsf, spring, etc. Both many versions later, so not new. I feel like projects that keep catering to legacy users are not helping this situation.

It gets even worse when you pull stuff from maven/gradle that has been built for 1.5. Which happened with trying to switch [byte-buddy from lombok to autovalue](https://github.com/raphw/byte-buddy/pull/400#issuecomment-361006248). Lombok has major issues under newer due to supporting older. Its creating a big mess for some things. There are only a handful of things that have such legacy requirements. Lombok, byte-buddy, and jclouds. Even gradle I was able to upgrade guava pretty trivially. Not sure why they are stuck on old versions. Intelliij was stuck on guava 18 for a while.

I do not believe bugs are fixed in older versions. Not sure why someone would want to remain running older vs newer. Seems they are not trying to keep their codebase current, or something. I just do not see it practical to be able to continue supporting legacy while being forward moving at the same time.

I do not see any way for Jclouds to support that many versions of guava, or even < guava 22. Likely have to bite the bullet, go to 1.8, and guava 22. Legacy users can remain with older versions of jclouds. Like they are already using older versions of Java and guava. Not to mention both 1.6 and 1.7 are long EOL. Anyone running that is either paying Oracle/IBM/RedHat for support, running openjdk/icedtea, to get around EOL from others. Basically running some what unsupported JDKs. I do not see how any of that should be encouraged. By now if people are not on 1.8. They have their own problems and should not be catered to.

The java world has changed. IMHO need to make sure you work with newer vs older. That is the new world and I much prefer it. Way to much legacy stuff still in wide usage. Projects that have not been updated in a long time. Some no longer in active development. One example is [jsch-agent-proxy](https://github.com/ymnk/jsch-agent-proxy/releases), but its not as outdated as other stuff from early 2000s...

Anyway I would say lets close this PR. I do not see any viable option for supporting Guava 21, nor would I bother. I recommend moving to 1.8, and guava 24. The gson problem is different preventing OSGi, so that is a blocker till code change. Guava is not. But there are changes in Guava 22, thus that version and anything newer should be fine. Older no go.

I can submit a new PR that should work for Guava 22+ and Java 1.8+. I think that is the route to go. I do not see this route being viable. Thus I think we should close. I can submit a new one for Guava 22+. It will require considerable less changes. I have sed to make those changes quickly. I really feel that is a better long term direction.

Please discuss that with community members. I can join ML or IRC if need be to help in discussion. I really do not see any options. There are simply to many changes required, and it will just cause issues later one. All for Guava 21, and I do not feel its worth while. Thus skipping that version.

**Comment by demobox** [comment]
> Thanks for the effort you put on this and for taking your time to have a look at it!

@wltjr Just wanted to add my thanks for trying to take this on to Ignasi's. Agree that the compatibility landscape has changed over time, and that a discussion about where to draw the line is certainly merited.

As Ignasi also pointed out, I think we need more data to understand what the impact would be before making any decisions. E.g. according to [the 2017 Plumbr report](https://plumbr.io/blog/java/java-version-and-vendor-data-analyzed-2017-edition) (from May), ~30% of JVMs that were detected were still at 7. That's not to say that that's an authoritative dataset, and of course it doesn't imply that the distribution of jclouds users looks similar. But, to me, it _does_ indicate that moving from 7 to 8 could have a significant impact, and would deserve more investigation, even if the world has moved on.

Would you be interested in helping by starting a discussion around compatibility on the [user](https://lists.apache.org/list.html?user@jclouds.apache.org) or [dev](https://lists.apache.org/list.html?dev@jclouds.apache.org) lists?

**Comment by wltjr** [comment]
@demobox Sure I can see about joining the lists. One route is also to keep a legacy version of jclouds. Like a 2.0.x branch, and then 2.1.x can be jdk 1.8 or newer. Seems odd that they would want a new jclouds, but other stuff old. Given other stuff likely has bugs fixed in newer updates.

Not sure if you all want to maintain 2 code bases and backport important stuff. That is another way to go. Many projects do have different releases for older versions and newer. Definitely other ways to go about all this. I think trying to do it all in one codebase is asking for trouble. Though some of the changes could be made on the fly for newer guava. That is [how I am doing it via sed](https://github.com/Obsidian-StudiosInc/os-xtoo/blob/master/dev-java/jclouds-core/jclouds-core-9999.ebuild#L55).

Which I can use some of that for more than just core, and submit new PR for guava 22+. There does not seem to be to many changes required for even guava 24 which I am building against, with java 9, etc. I should be moving onto 10 around the end of the month or before.

I think 2 code bases/branches maybe best for legacy support and moving forward. Rather than changing code based on guava versions etc.

You maybe right on Java usage, per various vendors life cycles.
http://www.oracle.com/technetwork/java/eol-135779.html
https://developer.ibm.com/javasdk/support/lifecycle/
https://access.redhat.com/articles/1299013

I feel like oracle is speeding things up to kill of legacy Java, and reduce competition Seems others tend to support older versions longer than Oracle. Which can explain continued usage of 1.7.  Likely means the same for 1.8, even when like Java 12+ comes out...

**Comment by wltjr** [comment]
Started a [discussion on dev mailing list](https://lists.apache.org/thread.html/904924028f0ba0e7e14a6f9e3fd52742ac9cd6bb6cdea0296f92fd1c@%3Cdev.jclouds.apache.org%3E)

**Comment by andreaturli** [comment]
Thanks @wltjr for your help with that!

**Comment by gaul** [comment]
I believe that f6d47b9c0eed7f2fa43f458e2d913305a21938ad supersedes this pull request.  If not, please reopen and rebase.
